### ISSUE TITLE
Drop Bower support?

### ISSUE THREAD

**Issue by patocallaghan** [yapplabs/ember-colpick#23]
👋 We use this addon in our app and are currently in the process of trying to move all of our dependencies entirely over to using yarn/npm.

Any thoughts on dropping the need for Bower to install this addon's dependencies? I'd be happy to put together the PR if you were open to the idea.

**Comment by lukemelia** [comment]
@patocallaghan I'd be very open to a PR that did this.

**Comment by patocallaghan** [comment]
@lukemelia great, I’ll take a stab at it next week

**Comment by patocallaghan** [comment]
Now in 1.0.0 🎉
